version: '3'

services:

  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  redis:
    image: "redis:alpine"

  web:
    build: .
    # command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    command: bash -c "cd /code/frontend && npm install && npm run build && cd /code/backend/ &&  python /code/backend/manage.py migrate --noinput && python /code/backend/manage.py collectstatic && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db
      - redis
    
  nginx:
    build: ./nginx
    volumes:
      - .:/code
    depends_on:
      - web

  celery:
    build: .
    command: celery -A backend worker -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data: