version: '3'

services:

  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  redis:
    image: redis:alpine
    command: redis-server
    expose:
      - 6379

  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/backend/static
      - media_volume:/code/backend/media
      - backend_volume:/code/backend/backend
    networks:
      - nginx_network
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/backend/static
      - media_volume:/code/backend/media
    networks:
      - nginx_network
    depends_on:
      - web
    ports:
      - 80:8000

  celery:
    build: .
    command: celery -A backend worker -l info
    # volumes:
    #   - backend_volume:/code/backend/backend
    depends_on:
      - web
      - redis
      - db

networks:
  nginx_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
  backend_volume: