version: '3'

services:

  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  redis:
    image: "redis:alpine"
    expose:
      - 6379

  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/backend/static
      - media_volume:/code/backend/media
      - backend_volume:/code/backend/backend
    expose:
      - 8000
    depends_on:
      - db
      - redis
    
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/backend/static
      - media_volume:/code/backend/media
    depends_on:
      - web
    expose:
      - 80

  celery:
    build: ./celery
    command: celery -A backend worker -l info
    volumes:
      - backend_volume:/code/backend/backend
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
  backend_volume: